version: '3.7'

services:
  postgres:
    image: bitnami/postgresql:latest
    ports:
      - '5432:5432'
    env_file:
      - ./.env
    volumes:
      - polls_pg_data:/bitnami/posrgresql

  redis:
    image: bitnami/redis:latest
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - '6379:6379'
    volumes:
      - polls_redis_data:/bitnami/redis/data

volumes:
  polls_pg_data:
    driver: local
  polls_redis_data:
    driver: local
