POST http://localhost:3333/polls
Content-Type: application/json

{
  "title": "What is your favorite color?",
  "options": [
    "Red",
    "Green",
    "Blue"
  ]
}

### 

GET http://localhost:3333/polls/157d2d35-8c30-4047-849c-cdffb054dda5

### 
POST http://localhost:3333/polls/157d2d35-8c30-4047-849c-cdffb054dda5/votes
Content-Type: application/json

{
  "pollOptionId": "e93ffa08-414a-4790-b07e-e1718e587a58"
}

# {
#   "pollOptionId": "cf4c12ce-5c90-435e-bda2-726854ef7a49"
# }